import { defineField, defineType } from 'sanity'
import { BulbOutlineIcon } from '@sanity/icons'

export const expertise = defineType({
  name: 'expertise',
  title: 'Expertise & Skills',
  type: 'document',
  icon: BulbOutlineIcon,
  fields: [
    defineField({
      name: 'name',
      title: 'Nome da Habilidade',
      type: 'string',
      description: 'Nome da tecnologia ou habilidade (ex: React, TypeScript, Node.js)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'iconName',
      title: 'Ícone',
      type: 'string',
      description: '🔍 Pesquise e selecione o ícone da tecnologia. Se não encontrar, selecione "✏️ Customizado" e use o campo abaixo.',
      options: {
        list: [
          // === OPÇÃO CUSTOMIZADA ===
          { title: '✏️ Customizado (usar campo abaixo)', value: 'CUSTOM' },
          { title: '───────────────', value: 'separator1' },
          
          // ===== ORDEM ALFABÉTICA =====
          { title: '✏️ Adobe', value: 'TbBrandAdobe' },
          { title: '💎 Adobe XD', value: 'SiAdobexd' },
          { title: '🅰️ Angular', value: 'SiAngular' },
          { title: '🅰️ Angular (Brand)', value: 'TbBrandAngular' },
          { title: '🤖 Android', value: 'FaAndroid' },
          { title: '🤖 Android (Brand)', value: 'TbBrandAndroid' },
          { title: '🔌 API', value: 'TbApi' },
          { title: '🍎 Apple', value: 'FaApple' },
          { title: '🍎 Apple (Brand)', value: 'TbBrandApple' },
          { title: '🚀 Astro', value: 'SiAstro' },
          { title: '☁️ AWS', value: 'SiAmazon' },
          { title: '☁️ AWS (Brand)', value: 'TbBrandAws' },
          { title: '☁️ Azure', value: 'TbBrandAzure' },
          { title: '🖥️ BitBucket', value: 'TbBrandBitbucket' },
          { title: '🅱️ Bootstrap', value: 'SiBootstrap' },
          { title: '🅱️ Bootstrap (Brand)', value: 'TbBrandBootstrap' },
          { title: '📦 Box', value: 'FiBox' },
          { title: '🔷 C', value: 'SiC' },
          { title: '➕ C++', value: 'SiCplusplus' },
          { title: '➕ C++ (Brand)', value: 'TbBrandCpp' },
          { title: '🔵 C#', value: 'SiSharp' },
          { title: '🔮 Chakra UI', value: 'SiChakraui' },
          { title: '🌐 Chrome', value: 'TbBrandChrome' },
          { title: '🔵 Circle', value: 'FiCircle' },
          { title: '☁️ Cloud', value: 'TbCloud' },
          { title: '💻 Code', value: 'FiCode' },
          { title: '⌘ Command', value: 'FiCommand' },
          { title: '📝 Contentful', value: 'SiContentful' },
          { title: '💾 CPU', value: 'FiCpu' },
          { title: '🎨 CSS3', value: 'SiCss3' },
          { title: '🌲 Cypress', value: 'SiCypress' },
          { title: '📊 D3.js', value: 'SiD3Dotjs' },
          { title: '🎯 Dart', value: 'SiDart' },
          { title: '💾 Database (Icon)', value: 'FiDatabase' },
          { title: '🐧 Debian', value: 'TbBrandDebian' },
          { title: '🖥️ Desktop', value: 'TbDeviceDesktop' },
          { title: '🖥️ Discord', value: 'TbBrandDiscord' },
          { title: '🎸 Django', value: 'SiDjango' },
          { title: '🎸 Django (Brand)', value: 'TbBrandDjango' },
          { title: '🐳 Docker', value: 'SiDocker' },
          { title: '🐳 Docker (Brand)', value: 'TbBrandDocker' },
          { title: '📰 Drupal', value: 'SiDrupal' },
          { title: '🌊 Edge', value: 'TbBrandEdge' },
          { title: '💧 Elixir', value: 'SiElixir' },
          { title: '🔧 ESLint', value: 'SiEslint' },
          { title: '🚂 Express', value: 'SiExpress' },
          { title: '⚡ FastAPI', value: 'SiFastapi' },
          { title: '🎨 Figma', value: 'SiFigma' },
          { title: '🎨 Figma (Brand)', value: 'TbBrandFigma' },
          { title: '🔥 Firebase', value: 'SiFirebase' },
          { title: '🦊 Firefox', value: 'TbBrandFirefox' },
          { title: '🌶️ Flask', value: 'SiFlask' },
          { title: '🎯 Flutter', value: 'SiDart' },
          { title: '🎬 Framer Motion', value: 'SiFramer' },
          { title: '📦 Git', value: 'FaGitAlt' },
          { title: '📦 Git (Brand)', value: 'TbBrandGit' },
          { title: '🔀 Git Branch', value: 'FiGitBranch' },
          { title: '🐙 GitHub', value: 'SiGithub' },
          { title: '🐙 GitHub (Brand)', value: 'TbBrandGithub' },
          { title: '🦊 GitLab', value: 'SiGitlab' },
          { title: '🦊 GitLab (Brand)', value: 'TbBrandGitlab' },
          { title: '🐹 Go', value: 'SiGo' },
          { title: '🐹 Golang (Brand)', value: 'TbBrandGolang' },
          { title: '☁️ Google Cloud', value: 'SiGooglecloud' },
          { title: '☁️ Google (Brand)', value: 'TbBrandGoogle' },
          { title: '🔷 GraphQL', value: 'SiGraphql' },
          { title: '⊞ Grid', value: 'FiGrid' },
          { title: '💿 Hard Drive', value: 'FiHardDrive' },
          { title: '🧮 Haskell', value: 'SiHaskell' },
          { title: '💜 Heroku', value: 'SiHeroku' },
          { title: '📄 HTML5', value: 'SiHtml5' },
          { title: '🧠 IntelliJ', value: 'SiIntellijidea' },
          { title: '☕ Java', value: 'FaJava' },
          { title: '📝 JavaScript', value: 'SiJavascript' },
          { title: '📝 JavaScript (Brand)', value: 'TbBrandJavascript' },
          { title: '🃏 Jest', value: 'SiJest' },
          { title: '📄 Joomla', value: 'SiJoomla' },
          { title: '🔬 Julia', value: 'SiJulia' },
          { title: '🤖 Kotlin', value: 'SiKotlin' },
          { title: '☸️ Kubernetes', value: 'SiKubernetes' },
          { title: '📄 LaTeX', value: 'SiLatex' },
          { title: '🎼 Laravel', value: 'SiLaravel' },
          { title: '🎼 Laravel (Brand)', value: 'TbBrandLaravel' },
          { title: '🧩 Layers', value: 'FiLayers' },
          { title: '🎨 Layout', value: 'FiLayout' },
          { title: '🎨 Less', value: 'SiLess' },
          { title: '🐧 Linux', value: 'FaLinux' },
          { title: '🌙 Lua', value: 'SiLua' },
          { title: '🐬 MariaDB', value: 'SiMariadb' },
          { title: '📝 Markdown', value: 'SiMarkdown' },
          { title: '🎭 Material UI', value: 'SiMui' },
          { title: '📊 Microsoft Office', value: 'FiPackage' },
          { title: '📱 Mobile', value: 'TbDeviceMobile' },
          { title: '🍃 MongoDB', value: 'SiMongodb' },
          { title: '🖥️ Monitor', value: 'FiMonitor' },
          { title: '🐬 MySQL', value: 'SiMysql' },
          { title: '🐱 NestJS', value: 'SiNestjs' },
          { title: '🌐 Netlify', value: 'SiNetlify' },
          { title: '▲ Next.js', value: 'SiNextdotjs' },
          { title: '▲ Next.js (Brand)', value: 'TbBrandNextjs' },
          { title: '💚 Node.js', value: 'SiNodedotjs' },
          { title: '💚 Node.js (FA)', value: 'FaNodeJs' },
          { title: '💚 Node.js (Brand)', value: 'TbBrandNodejs' },
          { title: '📝 Notion', value: 'SiNotion' },
          { title: '📦 npm', value: 'FaNpm' },
          { title: '📦 Package', value: 'FiPackage' },
          { title: '🐪 Perl', value: 'SiPerl' },
          { title: '⚡ Performance', value: 'FiZap' },
          { title: '🐘 PHP', value: 'SiPhp' },
          { title: '🐘 PHP (Brand)', value: 'TbBrandPhp' },
          { title: '🐘 PostgreSQL', value: 'SiPostgresql' },
          { title: '📮 Postman', value: 'SiPostman' },
          { title: '💅 Prettier', value: 'SiPrettier' },
          { title: '🐍 Python', value: 'SiPython' },
          { title: '🐍 Python (Brand)', value: 'TbBrandPython' },
          { title: '📊 R', value: 'SiR' },
          { title: '🚂 Railway', value: 'SiRailway' },
          { title: '🍓 Raspberry Pi', value: 'FaRaspberryPi' },
          { title: '⚛️ React', value: 'SiReact' },
          { title: '⚛️ React (FA)', value: 'FaReact' },
          { title: '⚛️ React (Brand)', value: 'TbBrandReact' },
          { title: '📱 React Native', value: 'TbBrandReactNative' },
          { title: '🔴 Redis', value: 'SiRedis' },
          { title: '🎩 Red Hat', value: 'TbBrandRedhat' },
          { title: '🎭 Remix', value: 'SiRemix' },
          { title: '💎 Ruby', value: 'SiRuby' },
          { title: '🦀 Rust', value: 'SiRust' },
          { title: '🦀 Rust (Brand)', value: 'TbBrandRust' },
          { title: '🧭 Safari', value: 'TbBrandSafari' },
          { title: '📄 Sanity', value: 'SiSanity' },
          { title: '💨 Sass', value: 'SiSass' },
          { title: '🎼 Scala', value: 'SiScala' },
          { title: '🖥️ Server', value: 'FiServer' },
          { title: '⚙️ Settings', value: 'FiSettings' },
          { title: '🎨 Sketch', value: 'TbBrandSketch' },
          { title: '💬 Slack', value: 'SiSlack' },
          { title: '💬 Slack (Brand)', value: 'TbBrandSlack' },
          { title: '📱 Smartphone', value: 'FiSmartphone' },
          { title: '⚡ Solid.js', value: 'SiSolid' },
          { title: '🍃 Spring', value: 'SiSpring' },
          { title: '⬜ Square', value: 'FiSquare' },
          { title: '🗄️ SQLite', value: 'SiSqlite' },
          { title: '📖 Storybook', value: 'SiStorybook' },
          { title: '🚀 Strapi', value: 'SiStrapi' },
          { title: '💅 Styled Components', value: 'SiStyledcomponents' },
          { title: '⚡ Supabase', value: 'SiSupabase' },
          { title: '🦅 Swift', value: 'SiSwift' },
          { title: '🔥 Svelte', value: 'SiSvelte' },
          { title: '🔥 Svelte (Brand)', value: 'TbBrandSvelte' },
          { title: '🎵 Symfony', value: 'FaSymfony' },
          { title: '📱 Tablet', value: 'FiTablet' },
          { title: '🎨 Tailwind CSS', value: 'SiTailwindcss' },
          { title: '🎨 Tailwind (Brand)', value: 'TbBrandTailwind' },
          { title: '📱 Telegram', value: 'TbBrandTelegram' },
          { title: '💻 Terminal', value: 'FiTerminal' },
          { title: '🎨 Three.js', value: 'SiThreedotjs' },
          { title: '🛠️ Tool', value: 'FiTool' },
          { title: '🔺 Triangle', value: 'FiTriangle' },
          { title: '📋 Trello', value: 'SiTrello' },
          { title: '📘 TypeScript', value: 'SiTypescript' },
          { title: '📘 TypeScript (Brand)', value: 'TbBrandTypescript' },
          { title: '🐧 Ubuntu', value: 'FaUbuntu' },
          { title: '🐧 Ubuntu (Brand)', value: 'TbBrandUbuntu' },
          { title: '▲ Vercel', value: 'SiVercel' },
          { title: '⚡ Vite', value: 'SiVite' },
          { title: '💚 Vue.js', value: 'SiVuedotjs' },
          { title: '💚 Vue (Brand)', value: 'TbBrandVue' },
          { title: '🎮 WebGL', value: 'SiWebgl' },
          { title: '📦 Webpack', value: 'SiWebpack' },
          { title: '💚 WhatsApp', value: 'TbBrandWhatsapp' },
          { title: '🪟 Windows', value: 'FaWindows' },
          { title: '🪟 Windows (Brand)', value: 'TbBrandWindows' },
          { title: '📰 WordPress', value: 'SiWordpress' },
          { title: '🧶 Yarn', value: 'FaYarn' },
          { title: '📹 Zoom', value: 'TbBrandZoom' },
          { title: '🔷 .NET', value: 'SiDotnet' },
        ],
        layout: 'dropdown',
      },
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'customIconName',
      title: 'Ícone Customizado',
      type: 'string',
      description: ' OPCIONAL: Se preferir usar um ícone do React Icons em vez de upload, digite aqui o nome EXATO (ex: SiFlutter, FaDocker, TbBrandVscode). Caso contrário, basta fazer upload do ícone no campo abaixo.',
      hidden: true,
    }),
    defineField({
      name: 'customIcon',
      title: 'Ícone Customizado (Upload)',
      type: 'image',
      options: {
        hotspot: true,
      },
      hidden: ({ parent }) => parent?.iconName !== 'CUSTOM',
      validation: (Rule) =>
        Rule.custom((customIcon, context) => {
          const iconName = (context.parent as any)?.iconName
          if (iconName === 'CUSTOM' && !customIcon) {
            return 'Campo obrigatório quando "Customizado" está selecionado'
          }
          return true
        }),
    }),
    defineField({
      name: 'color',
      title: 'Cor da Marca',
      type: 'string',
      description: 'Cor oficial da tecnologia em hexadecimal (ex: #61DAFB para React, #3178C6 para TypeScript)',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'categories',
      title: 'Categorias',
      type: 'array',
      description: '✅ Selecione uma ou mais categorias. Ex: TypeScript pode ser Linguagens + Frontend + Backend',
      of: [
        {
          type: 'string',
        },
      ],
      options: {
        list: [
          { title: '📝 Linguagens', value: 'languages' },
          { title: '📦 Frontend', value: 'frontend' },
          { title: '🖥️ Backend', value: 'backend' },
          { title: '💾 Base de Dados', value: 'database' },
          { title: '🛠️ Ferramentas', value: 'tools' },
        ],
        layout: 'grid',
      },
      validation: (Rule) => Rule.required().min(1).error('Selecione pelo menos uma categoria'),
    }),
    defineField({
      name: 'proficiencyLevel',
      title: 'Nível de Proficiência',
      type: 'number',
      description: 'Seu nível de conhecimento de 1 a 10 (1=Iniciante, 5=Intermediário, 10=Especialista)',
      validation: (Rule) => Rule.required().min(1).max(10),
    }),
    defineField({
      name: 'yearsOfExperience',
      title: 'Anos de Experiência',
      type: 'number',
      description: 'Quantos anos você trabalha com esta tecnologia (0-50 anos)',
      validation: (Rule) => Rule.min(0).max(50),
    }),
    defineField({
      name: 'description',
      title: 'Descrição',
      type: 'text',
      rows: 2,
      description: 'Breve descrição da sua experiência com esta habilidade. Aparecerá no modal de detalhes.',
    }),
    defineField({
      name: 'order',
      title: 'Ordem de Exibição',
      type: 'number',
      description: 'Ordem de aparição no portfólio. Números menores aparecem primeiro (ex: 1, 2, 3...)',
    }),
    defineField({
      name: 'featured',
      title: 'Habilidade em Destaque',
      type: 'boolean',
      description: 'Marque para destacar esta habilidade com uma estrela especial',
      initialValue: false,
    }),
  ],
  orderings: [
    {
      title: 'Display Order',
      name: 'orderAsc',
      by: [{ field: 'order', direction: 'asc' }],
    },
    {
      title: 'Category',
      name: 'categoryAsc',
      by: [{ field: 'category', direction: 'asc' }],
    },
    {
      title: 'Proficiency Level',
      name: 'proficiencyDesc',
      by: [{ field: 'proficiencyLevel', direction: 'desc' }],
    },
  ],
  preview: {
    select: {
      title: 'name',
      categories: 'categories',
      proficiency: 'proficiencyLevel',
      featured: 'featured',
    },
    prepare({ title, categories, proficiency, featured }) {
      const categoryLabels: Record<string, string> = {
        languages: '📝 Linguagens',
        frontend: '📦 Frontend',
        backend: '🖥️ Backend',
        database: '💾 Database',
        tools: '🛠️ Ferramentas',
      }
      const categoryText = categories && categories.length > 0
        ? categories.map((cat: string) => categoryLabels[cat] || cat).join(', ')
        : 'Sem categoria'
      
      return {
        title: featured ? `⭐ ${title}` : title,
        subtitle: `${categoryText} • Level ${proficiency}/10`,
      }
    },
  },
})
